version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Athens
      - PLEX_CLAIM=claim-TamTiiMTpi4zV9YijxyB
      - ADVERTISE_IP=http://192.168.205.4:32400/
    hostname: plexserver.example.com
    volumes:
      - /plex/database:/config
      - /plex/transcode:/transcode
      - /plex/media:/data